# Generated by Django 4.2.5 on 2023-10-12 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=100)),
                ('store_username', models.TextField(max_length=10)),
                ('store_password', models.TextField(max_length=10)),
            ],
            options={
                'ordering': ['store_name'],
            },
        ),
        migrations.CreateModel(
            name='vegetables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vege_name', models.CharField(max_length=50)),
                ('vege_descr', models.TextField()),
                ('vege_imag', models.ImageField(upload_to='')),
                ('vege_count', models.IntegerField(default=1)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_veg', to='front_farm.store')),
            ],
        ),
    ]
