# Generated by Django 4.2.5 on 2023-10-12 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front_farm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ['store1_name']},
        ),
        migrations.RenameField(
            model_name='store',
            old_name='store_name',
            new_name='store1_name',
        ),
    ]
