# Generated by Django 4.2.5 on 2023-10-14 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front_farm', '0003_vegetables_store_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vegetables',
            name='store_username',
        ),
    ]
