# Generated by Django 4.2.5 on 2023-10-14 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_farm', '0004_remove_vegetables_store_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vegetables',
            name='vege_imag',
            field=models.ImageField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='vegetables',
            name='vege_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
