# Generated by Django 4.2.5 on 2023-10-29 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_farm', '0005_alter_vegetables_vege_imag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vegetables',
            name='selected_category',
            field=models.CharField(blank=True, choices=[('vegetables', 'Vegetables'), ('fruits', 'Fruits'), ('flowers', 'Flowers'), ('home_products', 'Home Products')], max_length=20, null=True),
        ),
    ]
