# Generated by Django 4.2.5 on 2023-10-29 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_farm', '0006_vegetables_selected_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='store_address',
            field=models.TextField(default='Ravet , Pimpri Chinchwad , Pune , Maharashtra', max_length=500),
        ),
    ]
