# Generated by Django 4.2.5 on 2023-10-29 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_farm', '0008_user1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user1',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
