# Generated by Django 4.2.5 on 2023-11-01 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_farm', '0009_alter_user1_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='vegetables',
            name='vege_price',
            field=models.IntegerField(default=0),
        ),
    ]
